"""empty message

Revision ID: 3f82af35d67e
Revises: 
Create Date: 2019-05-24 07:49:20.596405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f82af35d67e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USER')
    op.drop_table('CATEGORY')
    op.drop_table('SUB_CATEGORY')
    op.drop_table('USER_EXTERNAL')
    op.drop_table('PRODUCT')
    op.drop_table('ORDER_DETAIL')
    op.drop_table('COMMENT')
    op.drop_table('VENDOR')
    op.drop_table('PHOTO')
    op.drop_table('EXTERNAL_PROVIDER')
    op.drop_table('PAYMENT')
    op.drop_table('ORDER')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ORDER',
    sa.Column('orderID', mysql.CHAR(length=20), nullable=False),
    sa.Column('orderDate', sa.DATE(), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='1-pending; 2-InProgress; 3-Done'),
    sa.Column('desiredTime', sa.DATE(), nullable=False),
    sa.Column('doneDate', sa.DATE(), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('commission', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ordererID', mysql.CHAR(length=20), nullable=False),
    sa.Column('shipperID', mysql.CHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ordererID'], ['USER.userID'], name='ORDER_ibfk_1'),
    sa.ForeignKeyConstraint(['shipperID'], ['USER.userID'], name='ORDER_ibfk_2'),
    sa.PrimaryKeyConstraint('orderID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('PAYMENT',
    sa.Column('paymentID', mysql.CHAR(length=20), nullable=False),
    sa.Column('method', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('userID', mysql.CHAR(length=20), nullable=False),
    sa.Column('orderID', mysql.CHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['orderID'], ['ORDER.orderID'], name='PAYMENT_ibfk_2'),
    sa.ForeignKeyConstraint(['userID'], ['USER.userID'], name='PAYMENT_ibfk_1'),
    sa.PrimaryKeyConstraint('paymentID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('EXTERNAL_PROVIDER',
    sa.Column('providerID', mysql.CHAR(length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('providerID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('PHOTO',
    sa.Column('photoID', mysql.CHAR(length=20), nullable=False),
    sa.Column('path', mysql.CHAR(length=100), nullable=False),
    sa.Column('productID', mysql.CHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['productID'], ['PRODUCT.productID'], name='PHOTO_ibfk_1'),
    sa.PrimaryKeyConstraint('photoID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('VENDOR',
    sa.Column('vendorID', mysql.CHAR(length=20), nullable=False),
    sa.Column('vendorName', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('vendorID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('COMMENT',
    sa.Column('commentID', mysql.CHAR(length=20), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('rate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ordererID', mysql.CHAR(length=20), nullable=False),
    sa.Column('shipperID', mysql.CHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ordererID'], ['USER.userID'], name='COMMENT_ibfk_1'),
    sa.ForeignKeyConstraint(['shipperID'], ['USER.userID'], name='COMMENT_ibfk_2'),
    sa.PrimaryKeyConstraint('commentID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ORDER_DETAIL',
    sa.Column('orderDetailID', mysql.CHAR(length=20), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('orderID', mysql.CHAR(length=20), nullable=False),
    sa.Column('productID', mysql.CHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['orderID'], ['ORDER.orderID'], name='ORDER_DETAIL_ibfk_2'),
    sa.ForeignKeyConstraint(['productID'], ['PRODUCT.productID'], name='ORDER_DETAIL_ibfk_1'),
    sa.PrimaryKeyConstraint('orderDetailID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('PRODUCT',
    sa.Column('productID', mysql.CHAR(length=20), nullable=False),
    sa.Column('productName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('barcode', mysql.TEXT(), nullable=False),
    sa.Column('userID', mysql.CHAR(length=20), nullable=False),
    sa.Column('subCategoryID', mysql.CHAR(length=20), nullable=False),
    sa.Column('vendorID', mysql.CHAR(length=20), nullable=False),
    sa.Column('productDescription', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['USER.userID'], name='PRODUCT_ibfk_2'),
    sa.ForeignKeyConstraint(['vendorID'], ['VENDOR.vendorID'], name='PRODUCT_ibfk_1'),
    sa.PrimaryKeyConstraint('productID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('USER_EXTERNAL',
    sa.Column('externalID', mysql.CHAR(length=20), nullable=False),
    sa.Column('externalUserID', mysql.CHAR(length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.CHAR(length=50), nullable=False),
    sa.Column('loginName', mysql.CHAR(length=50), nullable=False),
    sa.Column('userID', mysql.CHAR(length=20), nullable=False),
    sa.Column('providerID', mysql.CHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['providerID'], ['EXTERNAL_PROVIDER.providerID'], name='USER_EXTERNAL_ibfk_1'),
    sa.ForeignKeyConstraint(['userID'], ['USER.userID'], name='USER_EXTERNAL_ibfk_2'),
    sa.PrimaryKeyConstraint('externalID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('SUB_CATEGORY',
    sa.Column('subCategoryID', mysql.CHAR(length=20), nullable=False),
    sa.Column('subCategoryName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('categoryID', mysql.CHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['categoryID'], ['CATEGORY.categoryID'], name='SUB_CATEGORY_ibfk_1'),
    sa.ForeignKeyConstraint(['subCategoryID'], ['PRODUCT.subCategoryID'], name='SUB_CATEGORY_ibfk_2'),
    sa.PrimaryKeyConstraint('subCategoryID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('CATEGORY',
    sa.Column('categoryID', mysql.CHAR(length=20), nullable=False),
    sa.Column('categoryName', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('categoryID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('USER',
    sa.Column('userID', mysql.CHAR(length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phoneNumber', mysql.CHAR(length=20), nullable=False),
    sa.Column('email', mysql.CHAR(length=50), nullable=False),
    sa.Column('role', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='1-orderer 2-shipper 3-admin'),
    sa.Column('passwordHash', mysql.CHAR(length=50), nullable=False),
    sa.Column('avatarPath', mysql.CHAR(length=100), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Orderer-NULL; Shipper: 1-active, 2-inactive'),
    sa.Column('isBlocked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
